apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: nginx   # 👈 Add this label to match Service selector
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

      # Mount ConfigMap as index.html
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: pvc-storage
          mountPath: /var/log/nginx
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: DB_PASSWORD

      # Health checks
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

  volumes:
    - name: html-volume
      configMap:
        name: demo-config
        items:
          - key: index.html
            path: index.html
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: demo-pvc
